### ISSUE TITLE
Support for Qupzilla

### ISSUE THREAD

**Issue by jaerrib** [peppermintos/ice#13]
Currently, I use Ice with Firefox, but I'm also a KDE user and have gotten comfortable using Qupzilla as my regular browser. It would be great if Ice would be able to support it alongside the others.

**Comment by Mark-Peppermint** [comment]
I think we looked at Qupzilla and found no easy way to add support, but as I can't remember off the top of my head why, I'll take another look.

**Comment by akhkharuhymns** [comment]
Thanks for taking the time to look into things especially as Qupzilla is a lesser used browser than the ones you currently support.
