### ISSUE TITLE
Automatically create ~/.local/share/ice if not present

### ISSUE THREAD

**Issue by Mark-Peppermint** [peppermintos/ice#2]
Ice requires a folder to exist in the users home folder at
~/.local/share/ice
to save Firefox SSB's and icons.

This folder is currently added from
/etc/skel
as the user account is created, but if it goes missing (for any reason) it doesn't get recreated .. which also means ice isn't a standalone package that other distros can utilise.

Would it be possible for the script to check if the folder is present, and create it if not ?

If you haven't time Brian, I could probably handle this ?

**Comment by darthlukan** [comment]
Yeah, that can be easily checked for and added to the initialization of Ice.

**Comment by Mark-Peppermint** [comment]
Thanks Brian :)
