### ISSUE TITLE
add support for brave browser

### ISSUE THREAD

**Issue by gracy88** [peppermintos/ice#20]
from what ive read, brave browser full supports progressive web apps, any way to have support for Brave?

**Comment by Mark-Peppermint** [comment]
I've just tested the "--app" flag in Brave 0.25.2, and it still does nothing :(
Add to that, the fact Brave is now shipped as a snap, and doesn't open a URL from the CLI when you run say:-
brave https://peppermintos.com
it only seems to work when you access the snap binary directly .. as in:-
/snap/brave/34/usr/bin/brave https://peppermintos.com
and the Brave authors aren't making this easy (or even possible) :(

**Comment by gracy88** [comment]
brave-browser --app calls a window 

installed brave as this,

curl https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key add -

echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ `lsb_release -sc` main" | sudo tee -a /etc/apt/sources.list.d/brave-browser-release-`lsb_release -sc`.list

sudo apt update

sudo apt install brave-browser

--app flag apparently has been made to work in newest brave core Version 0.55.21 Chromium: 70.0.3538.77 (Official Build) (64-bit)

**Comment by Mark-Peppermint** [comment]
Thanks for this, I'll look into it as soon as I can.

**Comment by gracy88** [comment]
Awesome.   End game would be the ability to use brave browser's Tor private window as an option in Ice.   Ice Tor apps would be fantastic. 
  Otherwise Firefox works just fine.

**Comment by gracy88** [comment]
Awesome.   End game would be the ability to use brave browser's Tor private window as an option in Ice.   Ice Tor apps would be fantastic. 
  Otherwise Firefox works just fine.

**Comment by trymeouteh** [comment]
Please add Brave. Built in ad blocker makes this worth it!

**Comment by rhein** [comment]
BTW: brave is now supported with my latest PR. 
Migrated most of my apps and already saved a ton of ads ;-)
