### ISSUE TITLE
Include extensions for password management on ice-ssbs

### ISSUE THREAD

**Issue by gracy88** [peppermintos/ice#21]
The ability to use a password manager extension within the ice-ssb window would be beneficial.
For example, Gmail icessb, with bitwarden extension in window.

**Comment by Mark-Peppermint** [comment]
If using a browser based on Chromium (Chreomium/Chrome/Vivaldi) the plugins and extensions from the normal browser are used .. so if you have this extension in your browser, it'll be available in an SSB.

Firefox SSB's on the other hand all have their own separate profiles, so it's possible to install addons on a per SSB basis.

**Comment by gracy88** [comment]
Any instructions on the possibility for Firefox SSBs? I do not see this option in the software.

**Comment by Mark-Peppermint** [comment]
It's not in the ICE software, just hit the Alt key whilst in a Firefox SSB (to bring up the menu bar), then add your addons in the normal way
https://forum.peppermintos.com/index.php/topic,7269.msg74454.html#msg74454
and
https://forum.peppermintos.com/index.php/topic,2409.msg23784.html#msg23784

**Comment by michaldybczak** [comment]
> y instructions on the possibility for Firefox SSBs? I do not see this option in the software.

On Firefox it works the same as on Chrome/Chromium. If you have password manager installed (Bitwarden or Lastpass) and you enable automatic filling credentials, it works out of the box. In case it isn't, the option to fill credentials is available on the right-click in the box where it should be filled.

**Comment by Mark-Peppermint** [comment]
All SSB's now have the ability to have isolated profiles, so theoretically you can add your own addons, including a password manager (if you don't want to use the browsers default one).
