### ISSUE TITLE
New version 6 won't work due to missing folders

### ISSUE THREAD

**Issue by armageddon51** [peppermintos/ice#25]
Hello,

just install SSB version 6 on Manjaro. The application won't start and it was found that some folders needed are not created during build. The "profiles" folder once created manually fix the application.

~/.local/share/ice/profiles

**Comment by Mark-Peppermint** [comment]
That folder should be created when ice is run (and recreated if it's missing)

**Comment by armageddon51** [comment]
It seems that the folder is not created. I had earlier versions but I think that the ".../profiles" folder is new for this version (?). Anyway with the help from the Manjaro guys, we found out the error and create the folder manually. Then it start..

``/usr/bin/ice:721: DeprecationWarning: Gtk.Button.new_from_stock is deprecated
  apply_button = Gtk.Button.new_from_stock(Gtk.STOCK_APPLY)
Traceback (most recent call last):
  File "/usr/bin/ice", line 818, in <module>
    window = Ice()
  File "/usr/bin/ice", line 764, in __init__
    clean_orphaned_profiles(known_profiles)
  File "/usr/bin/ice", line 379, in clean_orphaned_profiles
    for fl in os.listdir("{0}/{1}/".format(_ICE_DIR, p_type)):
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/home/maurice/.local/share/ice/profiles/'

**Comment by Mark-Peppermint** [comment]
Are you up for testing a fix ?

If so, try changing the lines:-
```
_PROFILES_DIR = "{0}/profiles".format(_ICE_DIR)
_FF_PROFILES_DIR = "{0}/firefox".format(_ICE_DIR)
```
to
```
_PROFILES_DIR = "{0}/.local/share/ice/profiles".format(_HOME)
_FF_PROFILES_DIR = "{0}/.local/share/ice/firefox".format(_HOME)
```
in **/usr/bin/ice**

Then see if the **~/.local/share/ice/profiles** directory is automatically created when you run ice.
