### ISSUE TITLE
ice-ssb stopped working on Manjaro/Arch

### ISSUE THREAD

**Issue by michaldybczak** [peppermintos/ice#26]
I assume this is a general bug for Arch and Manjaro but I might be wrong. Anyway, after updating to 6.0.0-1 ice-ssb won't start and I get the output:

```
/usr/bin/ice:721: DeprecationWarning: Gtk.Button.new_from_stock is deprecated
  apply_button = Gtk.Button.new_from_stock(Gtk.STOCK_APPLY)
Traceback (most recent call last):
  File "/usr/bin/ice", line 818, in <module>
    window = Ice()
  File "/usr/bin/ice", line 759, in __init__
    details = get_details(a)
  File "/usr/bin/ice", line 72, in get_details
    for line in a:
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

So I downgraded the package to the previous version that worked in the past (5.3.4-1) but it turned out it has a similar issue:

```
/usr/bin/ice:551: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  where_lab = Gtk.Label(_("Where in the menu?"))
/usr/bin/ice:577: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  choose_icon = Gtk.Button(_("Select an icon"))
/usr/bin/ice:579: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  download_icon = Gtk.Button(_("Use site favicon"))
/usr/bin/ice:640: DeprecationWarning: Gtk.Button.new_from_stock is deprecated
  apply_button = Gtk.Button.new_from_stock(Gtk.STOCK_APPLY)
/usr/bin/ice:664: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  create_lab = Gtk.Label(_("Create"))
Traceback (most recent call last):
  File "/usr/bin/ice", line 732, in <module>
    window = Ice()
  File "/usr/bin/ice", line 676, in __init__
    nameline, pixbuf = get_details(a)
  File "/usr/bin/ice", line 69, in get_details
    for line in a:
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

**Comment by Mark-Peppermint** [comment]
in **/usr/bin/ice** try replacing all instances of:-

Gtk.Button.new_from_stock(Gtk.STOCK_CLOSE)
with:
Gtk.Button(label="Close")

and:
Gtk.Button.new_from_stock(Gtk.STOCK_OK)
with:
Gtk.Button(label="OK")

and:
Gtk.Button.new_from_stock(Gtk.STOCK_CANCEL)
with:
Gtk.Button(label="Cancel")

and:
Gtk.Button.new_from_stock(Gtk.STOCK_APPLY)
with:
Gtk.Button(label="Apply")

and:
Gtk.Button.new_from_stock(Gtk.STOCK_REMOVE)
with:
Gtk.Button(label="Remove")

and see if that makes any difference ?
(though I'm not sure that's the actual problem here)

**Comment by michaldybczak** [comment]
Still no :(

```
[michaldybczak@alienware-PC ~]$ ice
/usr/bin/ice:721: DeprecationWarning: Gtk.Button.new_from_stock is deprecated
  apply_button = Gtk.Button.new_from_stock(Gtk.STOCK_APPLY)
Traceback (most recent call last):
  File "/usr/bin/ice", line 818, in <module>
    window = Ice()
  File "/usr/bin/ice", line 759, in __init__
    details = get_details(a)
  File "/usr/bin/ice", line 72, in get_details
    for line in a:
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

**Comment by Mark-Peppermint** [comment]
You most likely have something in
~/.local/share/applications
that's not using utf-8 encoding .. maybe an archive ?

**Comment by michaldybczak** [comment]
Hmm.... Hard to say but how any file in this location could influence ice-ssb? Here is list of what is there:

```
[michaldybczak@alienware-PC applications]$ ls -lav
razem 61444
drwxr-xr-x   3 michaldybczak michaldybczak     4096 04-06 12:35  .
drwxr-xr-x 134 michaldybczak michaldybczak     4096 04-05 22:56  ..
-rw-------   1 michaldybczak michaldybczak       92 03-05 09:37  .directory
-rwxr-xr-x   1 michaldybczak michaldybczak      336 2016-11-04   FoxitReader.desktop
-rwxr-xr-x   1 michaldybczak michaldybczak      520 12-26 11:18  Intel-mode.desktop
-rwxr-xr-x   1 michaldybczak michaldybczak      521 12-26 11:17  Nvidia-mode.desktop
-rwxr-xr-x   1 michaldybczak michaldybczak      486 2018-05-25   appimagekit-outline-manager.desktop
-rwxr-xr-x   1 michaldybczak michaldybczak      544 12-20 10:56  appimagekit-raven-reader.desktop
-rw-------   1 michaldybczak michaldybczak      329 2017-10-13   chrome-aapocclcgogkmnckokdopfmhonfmgoek-Default.desktop
-rw-------   1 michaldybczak michaldybczak      327 2017-10-13   chrome-aohghmighlieiainnegkcijnfilokake-Default.desktop
-rw-------   1 michaldybczak michaldybczak      329 10-17 09:22  chrome-apdfllckaahabafndbhieahigkjlhalf-Default.desktop
-rw-rw-rw-   1 michaldybczak michaldybczak      325 2016-10-18   chrome-blpcfgokakmgnkcojhhkbfbldkacnbeo-Default.desktop
-rw-------   1 michaldybczak michaldybczak      301 04-02 08:29  chrome-egeogmlicipflbahncmbgckiblcmgnoe-Default.desktop
-rw-------   1 michaldybczak michaldybczak      325 2017-10-13   chrome-felcaaldnbdncclmgdcncolpebgiejap-Default.desktop
-rw-------   1 michaldybczak michaldybczak      487 10-30 10:34  chrome-kedcifahjjjlepgghlpifmfdlkkceikh-Default.desktop
-rw-------   1 michaldybczak michaldybczak      356 2018-04-04   chrome-nmmhkkegccagdldgiimedpiccmgmieda-Default.desktop
-rw-rw-rw-   1 michaldybczak michaldybczak      323 2016-10-18   chrome-pjkljhegncpnkpknbcohdijeoejaedia-Default.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      257 2016-03-05   chromium-app-list.desktop
-rw-------   1 michaldybczak michaldybczak      125 2017-10-16   ebook-viewer.desktop
lrwxrwxrwx   1 michaldybczak michaldybczak      152 04-03 07:24  epiphany-asana-409f3527310237bb8ef3d43846549d5082e89ebe.desktop -> /home/michaldybczak/.local/share/epiphany-asana-409f3527310237bb8ef3d43846549d5082e89ebe/epiphany-asana-409f3527310237bb8ef3d43846549d5082e89ebe.desktop
-rw-------   1 michaldybczak michaldybczak      501 11-22 22:27  gog_com-Baldurs_Gate_2_Enhanced_Edition_1.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak       97 2016-03-29   gwenview.desktop
-rw-r--r--   1 michaldybczak michaldybczak      338 2017-05-10   kdeconnect-sms.desktop
-rw-r--r--   1 michaldybczak michaldybczak      539 2017-04-08   konversation.desktop.old
-rw-rw-rw-   1 michaldybczak michaldybczak       93 2016-08-29   kwrite.desktop
-rw-------   1 michaldybczak michaldybczak      132 2017-02-05   libreoffice.desktop
-rw-------   1 michaldybczak michaldybczak      381 2017-01-11   megasync.desktop
-rw-r--r--   1 michaldybczak michaldybczak      487 2016-11-04   mimeapps.list
-rw-r--r--   1 michaldybczak michaldybczak     1727 02-18 16:09  mimeinfo.cache
-rw-------   1 michaldybczak michaldybczak       93 2017-03-19   mpv-2.desktop
-rw-r--r--   1 michaldybczak michaldybczak      615 2018-04-11   nixnote2.desktop
-rw-------   1 michaldybczak michaldybczak      333 2017-03-09   nvidia-settings-2.desktop
-rw-------   1 michaldybczak michaldybczak      526 01-22 22:10  obs.desktop
-rw-------   1 michaldybczak michaldybczak       98 2017-01-06   okular.desktop
-rw-------   1 michaldybczak michaldybczak      412 2017-03-03   openmw.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      134 2017-04-08   org.kde.konversation.desktop
-rw-rw-rw-   1 michaldybczak michaldybczak      324 2016-09-03   playonlinux.desktop
-rwxr-xr-x   1 michaldybczak michaldybczak 62626526 12-20 10:54  raven-reader-0.3.8-x86_64.AppImage
-rw-------   1 michaldybczak michaldybczak      859 2017-12-14   smplayer.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      159 2016-02-18   userapp-Firefox-O716CY.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      175 2016-02-17   userapp-Thunderbird-009CDY.desktop
-rw-------   1 michaldybczak michaldybczak       93 2017-11-19   vlc-2.desktop
drwxr-xr-x   3 michaldybczak michaldybczak     4096 2016-06-12   wine
-rw-------   1 michaldybczak michaldybczak      471 2017-02-13  'wine-Programs-Foxit Reader-Foxit Reader.desktop'
-rwxrwxrwx   1 michaldybczak michaldybczak      243 02-18 16:09  wine-extension-application.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      254 02-18 16:09  wine-extension-appref-ms.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      218 02-18 15:55  wine-extension-chm.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      247 02-18 16:09  wine-extension-compositefont.desktop
-rw-r--r--   1 michaldybczak michaldybczak      204 2018-02-05   wine-extension-dwg.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      225 02-18 15:55  wine-extension-gif.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      220 02-18 15:55  wine-extension-hlp.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      236 02-18 15:55  wine-extension-htm.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      237 02-18 15:55  wine-extension-html.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      232 02-18 15:55  wine-extension-ini.desktop
-rw-r--r--   1 michaldybczak michaldybczak      237 11-23 22:41  wine-extension-jar.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      228 02-18 15:55  wine-extension-jfif.desktop
-rw-r--r--   1 michaldybczak michaldybczak      241 11-23 22:41  wine-extension-jnlp.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      227 02-18 15:55  wine-extension-jpe.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      241 02-18 15:55  wine-extension-msp.desktop
-rw-rw-rw-   1 michaldybczak michaldybczak      223 02-18 15:55  wine-extension-pdf.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      225 02-18 15:55  wine-extension-png.desktop
-rw-r--r--   1 michaldybczak michaldybczak      235 2016-11-04   wine-extension-ppdf.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      215 02-18 15:55  wine-extension-rtf.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      210 02-18 15:55  wine-extension-txt.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      233 02-18 15:55  wine-extension-url.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      223 02-18 15:55  wine-extension-vbs.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      221 02-18 15:55  wine-extension-wri.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      271 02-18 16:09  wine-extension-xaml.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      264 02-18 16:09  wine-extension-xbap.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      223 02-18 15:55  wine-extension-xml.desktop
-rwxrwxrwx   1 michaldybczak michaldybczak      189 2017-07-03   wiznote.desktop
```

**Comment by michaldybczak** [comment]
Ah, something went wrong with copy/paste and I some strings weren't replaced as you suggested, so I re-checked it and did as you initially posted. Here is the result:

```
[michaldybczak@alienware-PC ~]$ ice
Traceback (most recent call last):
  File "/usr/bin/ice", line 818, in <module>
    window = Ice()
  File "/usr/bin/ice", line 759, in __init__
    details = get_details(a)
  File "/usr/bin/ice", line 72, in get_details
    for line in a:
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd8 in position 24: invalid continuation byte
```

**Comment by Mark-Peppermint** [comment]
Can you move everything from there to a new directory outside that directory except 
mimeapps.list
and
mimeinfo.cache
and then add them back one at a time until you find the offending item

I'm wondering if it's the 'wine' directory ?

**Comment by michaldybczak** [comment]
OK, I did move everything but the mimeapps.list and mimeinfo.cache but it was a bit too much probably:

```
[michaldybczak@alienware-PC ~]$ ice
Traceback (most recent call last):
  File "/usr/bin/ice", line 818, in <module>
    window = Ice()
  File "/usr/bin/ice", line 759, in __init__
    details = get_details(a)
  File "/usr/bin/ice", line 72, in get_details
    for line in a:
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd8 in position 24: invalid continuation byte
[michaldybczak@alienware-PC ~]$ ice
Traceback (most recent call last):
  File "/usr/bin/ice", line 818, in <module>
    window = Ice()
  File "/usr/bin/ice", line 764, in __init__
    clean_orphaned_profiles(known_profiles)
  File "/usr/bin/ice", line 379, in clean_orphaned_profiles
    for fl in os.listdir("{0}/{1}/".format(_ICE_DIR, p_type)):
FileNotFoundError: [Errno 2] Nie ma takiego pliku ani katalogu: '/home/michaldybczak/.local/share/ice/profiles/'
```
I still have the original /usr/bin/ice (copied it and renamed) so I can restore it just in case.

**Comment by Mark-Peppermint** [comment]
Manually create the directory
/home/michaldybczak/.local/share/ice/profiles

**Comment by michaldybczak** [comment]
Yay! That worked!

[michaldybczak@alienware-PC ~]$ ice
/usr/bin/ice:776: DeprecationWarning: Gtk.Button.new_from_stock is deprecated
  remove = Gtk.Button.new_from_stock(Gtk.STOCK_REMOVE)

and the ice window opens correctly. Now I will restore files one by one and see which one causes the trouble.

**Comment by Mark-Peppermint** [comment]
You should also replace
Gtk.Button.new_from_stock(Gtk.STOCK_REMOVE)
with
Gtk.Button(label="Remove")

but that's not critical

**Comment by michaldybczak** [comment]
Yeah, I noticed that and went through the list again (third time) and I again found those lines... They had to be multiple places because I saw how those lines changed and yet I found the old ones again. Anyway, I think I caught all of them because now when I launch ice, there is literally NO OUTOU, cursor moves to the next line which is empty so it's CLEAN :D. That rarely happens ;) .

**Comment by Mark-Peppermint** [comment]
That's two people who've reported that directory not being automatically created in Arch/Manjaro .. I'll need to look into that.
It **is** automatically created in Peppermint :-/

**Comment by michaldybczak** [comment]
Maybe pacman is somehow not ceating it from some reason. Check out the PKGBUILD of the ice-ssb AUR package.

Anyway, I found the offending file. It's raven-reader-0.3.8-x86_64.AppImage
In such case it's hard to check its content, or maybe it isn't? I suspect this is some kind of compressed or packaged file (like zip and similar) so maybe there is a way to check out its content.

However, I don't use this app so I could safely remove it. I usually relay on AUR and only when I can't find a package, I may use AppImage and then I just add them in this directory to know where to look for AppImage files just in case I needed to delete, replace them. So at the moment I can delete that file or at least not to put it there and the issue is gone.

I don't understand thou why ice-ssb has a problem with adjacent files which shouldn't have any influence on it (at least from my point of view)?

**Comment by Mark-Peppermint** [comment]
Okay thanks I'll leave this "Open" for now until I come up with a fix that ignores non-utf-8 encoded files .. and fixes the automatic directory creation .. then I'll release 6.0.1
Might be a while though, I'm in the middle of Peppermint 10 development.

**Comment by michaldybczak** [comment]
OK, thanks for help :).

I'll check if this new ice-ssb version solves the issue with the Plasma (that old, hijacking icon thread)

Maybe there is a way to add a manual action of creating that folder to this PKGBUILD. Who is the maintaner of ice-ssb AUR? Let him know about the problem. There is probably a way to add a command to check if that folder is there and create it if it's absent. PKGBUILDS are for to work around some things that are specific to certain distros. AUR packages that repackage rpm and debs always do that by removing some uncesseary and duplicated content from them.

**Comment by Mark-Peppermint** [comment]
I don't do the Arch builds, I just release the source here .. someone else does the AUR build.

**Comment by michaldybczak** [comment]
Well, PKGBUILDS aren't packages per se, only recipies so they just pull the package from some source (github, rpm, deb, etc.) and then make it work unpack and work for Arch. If some workarounds are needed, they are added in PKGBUILD.

So in some cases PKGBUILS are increadibly simple, in other cases they may be a bit complex or require some know-how, like it is case with git packages (and how versioning is counted)..

Just contact with the ice-ssb AUR maintainer and let him know about the issue and he may add the script to check and create this missing folder. You can also check in Manjaro live if the lack of the folder is some repeatable thing.

Anyway, maybe it would be better to close this thread as it is solved and then create two another ones with link to this one:

**

- Profile folder is not created during ice-ssb AUR install on Manjaro (possibly in Arch too)
- 
- Adjacent non-utf-8 files in ~/.local/share/applications/ prevent ice-ssb from launching

**

**Comment by Mark-Peppermint** [comment]
Can you try something for me...

in /usr/bin/ice
line 64 currently reads
    a = open(app, 'r')
can you change that to
    a = open(app, 'r', errors='ignore')
then add back that **raven-reader-0.3.8-x86_64.AppImage** file to
~/.local/applications
and see if ICE stiill works ?

**Comment by michaldybczak** [comment]
YES! That works! Ice starts correctly, without any output with the raven-reader-0.3.8-x86_64.AppImage file back in ~/.local/share/applications/

**Comment by Mark-Peppermint** [comment]
Cool .. please let me know if you get any other issues .. I'm not expecting this edit to cause any, but you never know :)

**Comment by michaldybczak** [comment]
Yeah. I understand. I'll create some chromium and firefox based apps and see if there are any other issues apart hijacking icon.

**Comment by Mark-Peppermint** [comment]
Thanks. It might also be handy to know if that icon hijacking on the latte dock thing is now solved .. at least with NEWLY created Firefox SSB's .. whilst the new version of ICE wasn't 'specifically' designed to solve that, it might.

**Comment by michaldybczak** [comment]
OK, created 2 apps on Chromium and the same ones for Firefox.
1. Chromium
Apps don't hijack browser icon anymore but on Chromium, they have their own icon when main Chromium is not launched. However, when Chromium is opened, the app is showing as another instance of the Chromium window. Closing both windows and then re-opening app alone makes it show proper app icon again. So the original issue is changed and actually is not so important as before, because initially, new app was always taking over the browser's icon which was a serious problem. Now it works well if the browser is not launched.

2. Firefox
All works correctly and as expected! No icon issues, no hijacking. Just perfect!

Another thing I noticed, I have vivaldi installed but it's grayed out on the list so I can't choose it from whatever reason. Not a problem for me.
I also have installed Epiphany (exactly for testing ssb's which this browser also can create) and ice seems not to notice it on the system, although this may be OK, since Epiphany can't be considered a normal, mainstream browser. The same about Falkon. I also have it installed and Ice-SSB isn't seeing it which I would consider also OK. Brave is also not detected, which is a bit surprising since it's Chromium-based, but maybe they changed it enough for ice-ssb not recognize it. Again, no problem.
You can't support all browsers so having the main ones should be enough.

And completely aside, I had some issue on Deepin with ice-ssb and it was not usable at all, but I don't remember what was exactly the problem. At this moment just ignore this, I may post a new Issue when I find the time. Or maybe the updated ice-ssb will work now correctly? I only tested the old version. Will see.

**Comment by Mark-Peppermint** [comment]
Nice, good to hear that's at least semi-solved :)

Is the vivaldi binary at
/usr/bin/vivaldi
in Arch/Manjaro ?

**Comment by michaldybczak** [comment]
Yeah, it's probably naming issue. The file is vivaldi-stable, but some builds may be called vivaldi or vivaldi-git etc. I installed vivaldi from this AUR package:

https://aur.archlinux.org/packages/vivaldi/

But many people are adding some additional repos, especially herakura's one ( https://wiki.archlinux.org/index.php/Unofficial_user_repositories#herecura ), who is one of the Arch maintainers so people are trusting in quality of his packages and from what I rember, vivaldi is also there so it may be named differently or maybe just vivaldi as it suppose to.

Is there a way to make the detection naming scheme less specific like vivaldi* or something like that? If that is in /usr/bin/ it should point out correctly the file, unless there are more similar files... Hm...

**Comment by Mark-Peppermint** [comment]
Would just symlinking
/usr/bin/vivaldi-stable --> /usr/bin/vivaldi
work ?

**Comment by michaldybczak** [comment]
vivaldi-stable is a symlink to /opt/vivaldi/vivaldi so I created a vivaldi link to that file too as I wasn't sure if making a symlink to a symlink is a good idea or even possible:

`sudo ln -s /opt/vivaldi/vivaldi /usr/bin/vivaldi`

and now vivaldi is no longer greayed out :)

Thanks :)
