### ISSUE TITLE
Feature request: access to ssb's settings

### ISSUE THREAD

**Issue by michaldybczak** [peppermintos/ice#27]
**Introduction:** I re-created ssb's on my work laptop on Manjaro with Deepin DE.  I mentioned in other thread that I had an issue in Deepin before, but it turned out that the ssb I created didn't show properly the icon for the desktop file. Deepin obviously checks that and without the icon, it isn't shown in the menu. Once the icon path is corrected manually, app shows up and everything is fine. _-> End of the introduction to the topic ;)._

I created ssb for my accounting-invoice app. I realized one big flaw. At some point of my work I need to save some files (pdf or zip files) on my disc but... I don't know where the app puts it. Even if I figure out where it is, I REALLY NEED:
- configure a path to store my files (it's my default work folder that I sync with a cloud)
- or allow the app to ask for the location

This is important for the workflow. So I already thought that this is a hopeless case but I figured out some workaround.

1. I created a copy of ssb's .desktop file
2. I edited the name of it to "name-properties"
3. Edited the exec path and instead the last piece of an url, I just put there "about:preferences" without quotation marks of course. All other lines were pointing to the same app container/profile

Here is how my .desktop file looked like for my app:

```
[Desktop Entry]
Categories=GTK;Office;
Comment=wfirma-ff-properties (Ice SSB)
Exec=firefox --class ICE-SSB-wfirmaff --profile /home/stolmetzywiec/.local/share/ice/firefox/wfirmaff --no-remote about:preferences
IceFirefox=wfirmaff
Icon=/home/stolmetzywiec/.local/share/ice/wfirma.png
MimeType=text/html;text/xml;application/xhtml_xml;
Name=wfirma-ff-preferences
StartupNotify=true
StartupWMClass=ICE-SSB-wfirmaff
Terminal=false
Type=Application
Version=1.0
X-Deepin-Vendor=user-custom
X-MultipleArgs=false
```

4. Close the ssb's window if it's opened (otherwise ff will complain about it's already been opened).
5. I launched such preferences app and I was presented with configuration page. I could set what I needed, closed the window.
6. I opened the main ssb app and this time it was launching a dialog to choose a place where to save a file, just like I set. As usual, ssb will remember the last used path so that works well for me, but now I can also set correctly a path without asking if I will.

This was all done on Firefox's ssb.

My request is: we really need a way to access preferences of created app's profile.

Putting the access icon on a gtk CSD bar as chrome/chromium is doing creates other issues (lack of SSD support for Plasma and other WMs).
My solution shows that WE CAN ACCESS preferences but it's inconvenient to go that route manually. So my proposal would be: have an option to create such additional properties launcher for a given app. Just a box to check. And if someone leaves it unchecked and wants to add it later, on the apps list it could be in the right-click menu to check or un-check (if someone wants to disable/delete such properties launcher).
Such launcher (.desktop file) would have schematized, automatic name: **app-name:properties** or something like that.
Of course, you can make this option active when Firefox or containerized version of other browser is created, otherwise, it could be grayed out (as it's unnecessary since then ssb inherits settings of the main browser).

I think this is a doable and very reasonable feature. It's maybe not ideal but it does the job. I think this could work for chromium based browsers as well. Preference pages for all supported browsers must be specified in ice-ssb.

**Comment by Mark-Peppermint** [comment]
Just hit Alt to access the menubar, then create an **about:preferences** bookmark.

See here:
https://forum.peppermintos.com/index.php/topic,8200.msg83969.html#msg83969

Ice v 6.0.1 (due soon) will have 3 bookmarks by default for Firefox SSB's
about:addons
about:config
about:preferences

**Comment by michaldybczak** [comment]
Alt doesn't work. I have global menus so I already have access to the menu, but that is not the problem. The problem is: those open pages like preferences in a new tab and ssb prevents that, so menus or alt just don't work.

So when I hit, for example, add a new bookmark, nothing is happening. All soft of menu interactions open sub-windows or another tab and that doesn't happen on ssb.

Ah, wait... I discovered that "open all bookmarks" is able to open some small, additional window with bookmarks. That way I can add preferences and addons.

When those bookmars are chosen, they really replace SSB window with those ones so they do work. Cool.

So now the only issue is the lack of discoverability for it, but that's a worry for another time. Still, my idea might work not just for FF but also Chromium-based browsers, so please consider adding in in some feature versions of ice-ssb. Having bookmarks is great but that works for FF only and is not intuitive to find.

I guess the maybe the same trick is possible with chromium based browsers? It's worth to test it later, but for now with FF it's for me enough.

**Comment by Mark-Peppermint** [comment]
ICE now comes with 4 bookmarks pre-configured in SSB's, just hit the Alt key to display the menubar, or hit Ctrl+Shift+O to open the bookmark manager .. you can the choose any of the 4 pre-configured bookmarks
about:addons
about:config
about:preferences
Firefox Keyboard & Mouse Shortcuts

**Comment by michaldybczak** [comment]
Are bookmarks updated on already existing webapps? I can't see those additional bookmarks. Or maybe they will be available in the version that is not in AUR yet?

**Comment by Mark-Peppermint** [comment]
Bookmarks for previous SSB's will not be changed, you'd need to delete or rename the 'places.sqlite' database in each of the SSB profile directories.
This command should rename them all
`find ~/.local/share/ice/firefox -iname 'places.sqlite' -execdir mv -i '{}' places.sqlite.old \;`
as for them only working once, dunno what's going on there .. maybe try updating the 2 files
/usr/bin/ice
and
/usr/bin/ice-firefox
with the contents from 6.0.4 (if the AUR has an older version).

**Comment by michaldybczak** [comment]
I found out that making "restore session" causes bookmarks to stop working. Also, unchecking "open links in new tabs" helps, because I don't have to right-click anymore on links that don't do anything (because they are suppose to open tabs, they can't so nothing is happening) and now those links autmatically open new windows so it's an improvement :).

Anyway, I though, is there any way to make such settings like uncheck" "open links in new tabs" default on new app? This way FF apps would behave more correctly from the start. It's not a priority but it would be nice to have default FF settings that work best with app container.

**Comment by Mark-Peppermint** [comment]
You cold add the line
`os.system('user_pref("\\browser.link.open_newwindow"\\, 1);" > ' + profilepath + '/user.js')`
just above the line
`os.system('echo "user_pref(\\"browser.cache.disk.enable\\", false);" > ' + profilepath + '/user.js')`
in /usr/bin/ice-firefox
But personally I just use Ctrl+Tab to navigate between hidden tabs

**Comment by michaldybczak** [comment]
Hidden Tabs? Heh? What does it mean?

If I click a link and it supposes to open in a tab and looks like nothing happens, in reality, opens tab somewhere in limbo ;) and I can switch to it with ctrl+tab?

**Comment by Mark-Peppermint** [comment]
When you elect to open a link in a new tab, the tab DOES open, it's just hidden .. but you can navigate between ten with Ctrl+Tab

**Comment by Mark-Peppermint** [comment]
BTW, a better option that disables "Open links in tabs instead of new windows" in NEW SSB's but will still allow you to change back would be to make the change in /usr/bin/ice rather than /usr/bin/ice-firefox.

Edit /usr/bin/ice and change the section
```
    os.system("touch {0}".format(settingsfile))
    with open(settingsfile, 'w') as sfile:
        sfile.write('user_pref("browser.cache.disk.enable", false);')
```
to
```
    os.system("touch {0}".format(settingsfile))
    with open(settingsfile, 'w') as sfile:
        sfile.write('user_pref("browser.link.open_newwindow", 1);')
        sfile.write('user_pref("browser.cache.disk.enable", false);')
```

**Comment by michaldybczak** [comment]
Cool. Didn't know that. So many years of using various browsers and something still can surprise me ;).

Anyway, I like how ice-ssb developed lately. UI is simplistic and yet the usage requires some specific know-how.
Thanks again for this great piece of software :).

**Comment by Mark-Peppermint** [comment]
You're most welcome :)
