### ISSUE TITLE
Add checking for running instances of browser

### ISSUE THREAD

**Issue by Sandmonster** [peppermintos/ice#28]
To describe my issue here is example:

I have some chat application, when somebody sends me a link it gets opened in my default browser (Chromium). If instance of chromium is already running a tab with this link gets opened in this instance.

This is the flow I got used to

Now, when I create Chromium application with Ice I also sometimes encounter links to external sites. When I click this links a new instance of Chromium gets started to open it, but new instance gets started even if there are already running instances of Chromium and I would like links to external sites to be opened in already running instances of Chromium instead of creating new ones.

**Comment by Mark-Peppermint** [comment]
Create the Chrome/Chromium SSB with an isolated profile (so it can have its own addons)
Open the SSB
Hit Ctrl+n (to open a new window)
Go to:-
https://chrome.google.com/webstore/detail/open-link-in-same-tab-pop/jmphljmgnagblkombahigniilhnbadca?hl=en
and install that addon
Close all the SSB windows.
Reopen the SSB .. any links you click will now be opened in the same window.

You can achieve a LOT with isolated profiles and different addons.

**Comment by Sandmonster** [comment]
@Mark-Peppermint well, this is not exactly what I was looking for. But you mentioned profile isolation and I  created the same application without profile isolation just to see how it would work and it worked exactly what I wanted it to be. 

So, when clicking link in profile isolated application it spawns it's own isolated instances of Chromium instead of opening it in general Chromium instance. But when application is not isolated it would open links in general instance.

I'm curious about why isolated application would open external links in isolated browser? To me it seems that when you create isolated application, you want isolated addons to be related only to specified site inside application, but all external links I would like to be viewed in my general instance of Chromium.

To illustrate this example:
I have ad block installed in my general chromium instance, cause when I browse internet I don't want to see annoying ads. At my job we use Mattermost for any kind of messaging. I don't want to keep Mattermost tab in my general instance, because usually during my work I get tons of other tabs opened and it's hard to navigate back to Mattermost tab among them. So, I create Mattermost application with Ice and also make it isolated, because Mattermost has no ads in it and I don't want browser to even bother looking for them. If someone sends me a link to external site I want it to be opened in my general instance because external site may have ads, which I don't want to see. But isolated application opens external links in isolated chromium instances without ad block addon.

While this may be the easiest implementation of ssb, it's doesn't seem to be right ideologically for me. 
To me it's not critical, I can just go on without isolation, but maybe other people would like it to be as I described. Maybe one more option when creating application to ask if user wants to open external links to be opened in general or isolated instance of browser would be good.

**Comment by Mark-Peppermint** [comment]
You're misunderstanding "isolation", it's web browser "profile isolation" not "window isolation".
