### ISSUE TITLE
Prevent user from creating a web-app without name.

### ISSUE THREAD

**Issue by Coeur-Noir** [peppermintos/ice#29]
Hello,

ICE is a very nice utility ! For kiosk setups, but non only !

It may lack though a little safety trick : it is now ( version ice_6.0.3_all.deb ) possible to create a web-app without naming it.

Since from « name » depends creation of web-app's profile folder, it may end in a messy situation regarding web-app profiles stored then in
`~/.local/share/ice/firefox/`
instead of
`~/.local/share/ice/firefox/web-app-name`
and it creates in
`~/.local/share/applications`
an obviously hidden .desktop file ( ok you really _have to_ want to launch that one but that may happen… )

**Maybe the « apply » button should stay inactive as long as the « name app » box is empty ?**

_For reference ( french ) : https://forum.ubuntu-fr.org/viewtopic.php?pid=22106126#p22106126 where I still think the_ op _issue is not related to ICE._

And question : where may I help translate ICE in french ? ( solved )

**Comment by pshem** [comment]
I thought ICE already had a French translation? If you're not seeing it, that might be because ICE uses the language based on the OS langauage(defined by the `LANG` environment variable if I remember correctly). You can view your environment variables with `env`.

The language files are in https://github.com/peppermintos/ice/tree/master/usr/share/ice/locale/fr, you edit the `.po` file and compile it to create a `.mo` by running `msgfmt messages.po -o messages.mo`(based on https://stackoverflow.com/a/39643149, the command worked for me to create the Polish translation ages ago).

**Comment by Coeur-Noir** [comment]
Indeed ! Regarding translation, it was just a temporary bug solved by https://github.com/peppermintos/ice/commit/1312ee9e9f3395e61740baf72388ef1193836e23 in v6.0.4.

Any thought about preventing creation of unnamed ssb launcher ?

**Comment by pshem** [comment]
You'd need to throw an error in the code verifying the validity of an app a user tries to create: https://github.com/peppermintos/ice/blob/1312ee9e9f3395e61740baf72388ef1193836e23/usr/bin/ice#L213-L248

You could add this in line 247: 
```python3
elif len(title) == 0 or not title.printable:
    InvalidNameError(title, formatted, address, iconext, location)
```

and create an `InvalidNameError` class. This would probably be accomplished simultaneously with creating a generic error class other errors inherit from, to reduce code duplication between errors. There already are:
- `NoBrowserError`,
- `DuplicateError`,
- `AddressError`.
They share the:
- `destroy()` function
- most of the `init()` function
So the time to reduce duplication is now. I've never actually written any objective oriented Python before, so I might try to do this.

**Comment by Mark-Peppermint** [comment]
Fixed in v6.0.5
Thanks pshem for the way forward.

**Comment by Mark-Peppermint** [comment]
Fixed in v6.0.5
Thanks to **pshem** for the way forward.

**Comment by pshem** [comment]
@Mark-Peppermint GJ, you're quick.

**Comment by Mark-Peppermint** [comment]
TVM @pshem it wouldn't have been so quick without your input, that's for sure :+1:
