### ISSUE TITLE
Package up for a new Release

### ISSUE THREAD

**Issue by thunderstorm99** [peppermintos/ice#3]
Hey there everyone.
Thanks for providing this awesome program, however the most recent release 5.1.4 has this major bug of not creatinng the ~/.local/share/ice/ folder. Could you provide a new Release from master?
Thanks in advance!

**Comment by darthlukan** [comment]
I've gone ahead and created a tag for v5.1.8. Our usual packager, @Mark-Peppermint , manages the PPA so I won't go stepping on his toes. Chances are that you'll see an update within the next couple of days, but if not, leave a comment here and we'll get things sorted. I'll leave this issue open until the package is in the PPA or until @Mark-Peppermint responds.

**Comment by Mark-Peppermint** [comment]
Cheers Brian, I could have sworn we'd already dealt with the bug where it wasn't creating
~/.local/share/ice/
But I'll give this version a good testing, then hopefully package it up later today or tomorrow.

I'll post back here when it's available in our PPA

**Comment by Mark-Peppermint** [comment]
My mistake, I've been running 5.1.8 on Peppermint 6 for some time (so it's already well tested), but I'd only packaged it for xenial in the peppermintos/p7-dev PPA:
https://launchpad.net/~peppermintos/+archive/ubuntu/p7-dev
I *could* package it for Peppermint 6, but I wasn't going to bother as I didn't want the button placement flip to confuse people.

**Comment by darthlukan** [comment]
Yep, 5.1.8 should arguably only go in P7 at this point. Others can build from the sources by pulling the latest tagged release (as happened in issue #4 ).

**Comment by Mark-Peppermint** [comment]
Cheers Brian.

**Comment by thunderstorm99** [comment]
Thanks @Mark-Peppermint and @darthlukan for the Quick response. We now have 5.1.8 on arch.

**Comment by Mark-Peppermint** [comment]
You're most welcome @thunderstorm99 .. as Brian said it's great to see it being utilised by other distributions :)
