### ISSUE TITLE
Similar project for Android Chromium browsers?

### ISSUE THREAD

**Issue by xRadio-us** [peppermintos/ice#31]
The SSB concept would seem to be ideal for creating simple Android apps out of simple web sites like https://xradio.us/mini-college.php Could you recommend a good ICE alternative for Android?

**Comment by Mark-Peppermint** [comment]
Sorry, but I don't know of an Android alternative, and we currently have no plans to make an Android version of ICE.

**Comment by pshem** [comment]
@xRadio-us This is implemented on android in Firefox and Chrome, and called PWAs, progressive web apps. For example in Firefox on Android some application show a :house:+ symbol on the URL bar and you can make them into SSBs that get their own icon on the home screen.
One domain you can test on is https://theregister.co.uk

 One difference compared to ICE is that it requires website owner buy in(through the creation of an app manifest)

**Comment by hackel** [comment]
See https://github.com/tobykurien/WebApps
