### ISSUE TITLE
New Firefox SSBs include tab bar and nav bar -- must set toolkit.legacyUserProfileCustomizations.stylesheets true

### ISSUE THREAD

**Issue by AndydeCleyre** [peppermintos/ice#34]
Currently using

ice-ssb `6.0.5`
firefox `70.0.1`
Arch Linux

Some time after Firefox `68.0.2`, custom user chrome style became disregarded by default, now a "legacy" option.

Here's a Google Maps Firefox-SSB that I created in the past which hides the elements, next to a newly created Last.fm Firefox-SSB which does not:

![image](https://user-images.githubusercontent.com/1787385/68040723-4a6d6f00-fca5-11e9-9370-7f4ab5874bf2.png)

This can be fixed, at least for now, by setting Firefox's `toolkit.legacyUserProfileCustomizations.stylesheets` to `true`.

**Comment by Mark-Peppermint** [comment]
Thanks Andy, this should have already been fixed in ICE 6.0.6

**Comment by AndydeCleyre** [comment]
Haha, whoops. I just implemented the fix only to notice it was already there. Thanks!
