### ISSUE TITLE
.rpm or flatpak support?

### ISSUE THREAD

**Issue by perrsona1234** [peppermintos/ice#35]
Hi.

I was wondering, if You could create an .rpm build (or something that works crossplatform e.g. flatpak) of this great tool?

I used it alot on Debian-based distros, but I'm on openSUSE now, and I can't find a way to get this tool again. I use Firefox, so installing Chromium (or any other browser that supports it) just for this particular feature is an overkill for me.

Thank You.

**Comment by Mark-Peppermint** [comment]
Sorry, we don't package ICE for anything other than Peppermint. We make the code available in case others wish to package it for other formats, for example someone packages it for the Arch user repository, but we have no plans to package it for anything other than Peppermint.

**Comment by JuPlutonic** [comment]
AppImage(#32) / alien `alien -r ice.deb` are okish soluions for openSUSE, Fedora, etc
