### ISSUE TITLE
Add Ungoogled Chromium Browser!

### ISSUE THREAD

**Issue by trymeouteh** [peppermintos/ice#39]
Chromium is good but it still has some evil Google code. Please add Ungoogled Chromium as an option for those who want basic vanilla chrome that has strong privacy and is google free.

https://github.com/Eloston/ungoogled-chromium

https://alternativeto.net/software/ungoogled-chromium/

**Comment by Mark-Peppermint** [comment]
We're unlikely to add ungoogled-chromium as an option in ICE, it's simply not big enough.

That said, there is nothing stopping you creating a symlink from wherever ungoogled-chromium puts its binary to:
/usr/bin/chromium-browser

then any ICE SSB's set to use chromium-browser should open in ungoogled-chromium
