### ISSUE TITLE
tag more versions

### ISSUE THREAD

**Issue by benneti** [peppermintos/ice#4]
I think the current version is 5.1.8 but the last tagged is 5.1.4, is there a reason for this or would it be possible to tag the new versions, too?
(I'm asking because this would make it easier to make a PKGBUILD for archlinux with the recent version)
Thank you for this nice application :+1:

**Comment by darthlukan** [comment]
Tag v5.1.8 has been created based on the latest commit from master. The issue was that the last committer forgot to create the tag. Thanks for packaging Ice for Arch, it's nice to see the software is usable for more types of users :)

**Comment by benneti** [comment]
Thank you :)
