### ISSUE TITLE
Back Button

### ISSUE THREAD

**Issue by trymeouteh** [peppermintos/ice#43]
Please add an option to have a back button on the top of the SSB.

**Comment by Mark-Peppermint** [comment]
We'll not add any kind of navigation bar to SSB's as it kind of defeats the purpose. If you want a navigation bar open the site in a regular browser.
You can however still use keyboard shortcuts such as Alt+⇦ or Ctrl+[
http://7is7.com/software/firefox/shortcuts.html
As you can use Alt to open the menu bar to get at settings .. you'll also find some useful bookmarks already set up:-
Addons
Config (about:config)
Preferences
Firefox Keyboard & Mouse Shortcuts (which takes you to the link above listing the keyboard/mouse shortcuts)

**Comment by trymeouteh** [comment]
I understand, I thought it will make a good feature since I made a YouTube app with Ice and when I click on a video, and then click on another video in the related videos list but want to go back to the previous video a back button would be nice.
