### ISSUE TITLE
ice-ssb locks after clicking 'Use site favicon' or 'Apply'

### ISSUE THREAD

**Issue by krg1966** [peppermintos/ice#6]
I'm using 'ice-ssb 5.2,3-1' from aur on newly installed 64bit Manjaro xfce, work previously on Manjaro KDE fine. 

My ~/.local/share/ice/ folder exists, nothing in it yet.

When lauching from terminal, I see the message below, but not sure if this is really an issue based on some articles I've read saying it can be ignored.
"/usr/bin/ice:21: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk"

No other messages from terminal, if I close without clicking the buttons mentioned earlier.  If I do click them I have to forcibly close Ice.

All files listed from below are present:
/usr/bin/chromium-browser
/usr/bin/google-chrome
/usr/bin/ice
/usr/bin/ice-firefox
/usr/lib/peppermint/ice/ice.glade
/usr/share/applications/ice.desktop
/usr/share/applications/pixmaps/ice.png

I have uninstalled and installed again, any help on what to troubleshoot next would be great.  Is there a verbose switch?

**Comment by Mark-Peppermint** [comment]
The "PyGIWarning" warning shouldn't affect the running of ice, but if you want to get rid of it add the two lines:

import gi
gi.require_version('Gtk','3.0')

just above the line:-

from gi.repository import Gtk

Might be worth seeing if changing the line:-

soup = BeautifulSoup(markup)

to

soup = BeautifulSoup(markup, "lxml")

makes any difference to the lockup ?

I take it you do have "python-beautifulsoup" installed ?

**Comment by krg1966** [comment]
The lines:
import gi
gi.require_version('Gtk','3.0')
did fix the PyGIWarning!

I added the , "lxml" to soup = BeautifulSoup(markup)

Tried each individually, neither help with the issue previously described.

I do have "python-beautifulsoup4     4.5.1-1" installed.  I reinstalled it, did not help.  Will restart and write back only if that helps.

I see the following available for install, but not sure if I need to try installing them or not:
python2-beautifulsoup3     3.2.1-3
python2-beautifulsoup4     4.5.1-1

Any other ideas?

Thank you for the quick response and things to try!

**Comment by krg1966** [comment]
I'll close this issue.  Unfortunately, I have no idea why but Ice is working for me now.  I tried it after a new install.  Abandoned it to finish setting up my system, I just decided to try it again and it worked like a charm.  I guess some other applications that I have installed put the missing piece I needed on the machine.  Ice is working fine now.  ~Thanks

**Comment by darthlukan** [comment]
Just for reference, could you please provide us the output of "pip freeze" so that we can see which Python libraries you have installed and can compare that to what we list as dependencies? There may be a library version which we did not previously consider that we possibly should. Please and Thank You :)

**Comment by krg1966** [comment]
I will tonight

Sent from my iPhone

On Jan 19, 2017, at 11:58 AM, Brian Tomlinson <notifications@github.com<mailto:notifications@github.com>> wrote:


Just for reference, could you please provide us the output of "pip freeze" so that we can see which Python libraries you have installed and can compare that to what we list as dependencies? There may be a library version which we did not previously consider that we possibly should. Please and Thank You :)

-

**Comment by krg1966** [comment]
Here is the output you requested:
$ pip freeze
appdirs==1.4.0
beautifulsoup4==4.5.3
catfish==1.4.2
CDApplet==1.0
CDBashApplet==1.0
chardet==2.3.0
cupshelpers==1.0
gufw==17.4.1
lightdm-gtk-greeter-settings==1.2.1
louis==3.0.0
lxml==3.7.2
menulibre==2.1.3
mugshot==0.3.2
packaging==16.8
pacman-mirrors==3.0.0
pexpect==4.2.1
psutil==5.0.1
ptyprocess==0.5.1
pycups==1.9.73
pycurl==7.43.0
pygobject==3.22.0
pyparsing==2.1.10
python-distutils-extra==2.39
python-libtorrent==1.1.1
pyxdg==0.25
requests==2.12.4
six==1.10.0
team==1.0
urllib3==1.19.1

Let me know if you need anything else.
