### ISSUE TITLE
SSB with Firefox just opens once

### ISSUE THREAD

**Issue by meiser79** [peppermintos/ice#69]
Hi,

I'm using ice SSB together with Firefox 79.0 under Ubuntu 20.04.

I created a SSB for Threema (https://web.threema.ch). The page opens after creation, but if I close the SSB and re-open it, only a blank site is shown.
I have to re-create the profile with ice-firefox so that it opens again once.

I can also reproduce the issue with WhatsApp Web (https://web.whatsapp.com), but not with https://my.jdownloader.org

Thanks for your help.
Regards,
meiser79

**Comment by JuPlutonic** [comment]
Looking interesting, do my Firefox 79 Development Edition working well with Slack. How about the new 80 version of Firefox?

**Comment by meiser79** [comment]
Thanks for the hint, I checked again after the recent update to Firefox 80 on Ubuntu 20.04. It seems to work fine now.

**Comment by meiser79** [comment]
The issue is back after Firefox upgrade to 81.0+build2-0ubuntu0.20.04.1
