### ISSUE TITLE
Altering default search

### ISSUE THREAD

**Issue by pshem** [peppermintos/ice#8]
When you right click on a link, you get a standard set of options, ie. 
* Open, 
* Open in a new Tab, 
* Search with Google…

That last one annoys me to no end because it requires going through Google's privacy statement(because it's a new profile) before you actually make the search and I:
a) often click it accidentally(it's just below the new tab which I usually want),
b) don't want to search with Google.
Can ICE include code to change the default search provider to [http://ddg.gg](url), like the rest of Peppermint, or remove the search option from the right click menu entirely, to reduce misclicks?

I'd be happy to help write this feature, although my Python is not very good

**Comment by Mark-Peppermint** [comment]
Default search engine for Firefox SSB's is now set to DuckDuckGo in the latest v5.2.5 version.

**Comment by pshem** [comment]
Awesome, thank you!

**Comment by Mark-Peppermint** [comment]
If you're using an Ubuntu/Debian based distro, you can find 5.2.5 pre-packaged in our p7-dev PPA here:
https://launchpad.net/~peppermintos/+archive/ubuntu/p7-dev/+files/ice_5.2.5_all.deb

**Comment by pshem** [comment]
I'm using Peppermint 7 so I'll reach me anyway. I'll try adding the dev PPA to help with testing though

**Comment by Mark-Peppermint** [comment]
I wouldn't add the PPA .. just download the .deb, or wait till I've finished testing and push it as an update ;)
