### ISSUE TITLE
Firefox 97 No title bar in Gnome 40.x

### ISSUE THREAD

**Issue by pellcorp** [peppermintos/ice#85]
When I create Ice profiles for websites using firefox there is no title bar.   Im not sure if this is restricted to gnome or not.

**Comment by pellcorp** [comment]
I disabled the `user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true); ` setting in the profile and it restored the title but also the location so not an ideal solution at all.

**Comment by pellcorp** [comment]
Ah Im playing around with the chrome/userChrome.css to see if I can find a combination that restores the title bar but nothing else.

**Comment by pellcorp** [comment]
I discovered that the following userChrome.css restores the title:

```
#nav-bar, #identity-box, #tabbrowser-tabs { visibility: collapse !important; }
```
So remove the `, #TabsToolbar` only

**Comment by pellcorp** [comment]
https://github.com/peppermintos/ice/pull/86

**Comment by grafiksinc** [comment]
This is not maintained anymore.....we moved to CodeBerg...and the ICE application is being rewritten using pyqt5....if you are interested in helping build that do contact us over at matrix look for the PeppermintOS channel
